#!/bin/bash
# Vendor the mustache.js UMD bundle into hooks/lib/vendored/mustache.js.
#
# Usage: ./scripts/update-mustache-vendor.sh <version>   # e.g., 4.2.0
#
# The rule-runner loads this via require('./vendored/mustache.js') to render
# emit: templates in rule files. Vendoring keeps the hook layer zero-npm-dep
# (§4.9 of ~/dev-projects/ido4-suite/docs/hook-and-rule-strategy.md).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
VENDOR_DIR="$PLUGIN_DIR/hooks/lib/vendored"
BUNDLE_FILE="$VENDOR_DIR/mustache.js"
VERSION_FILE="$VENDOR_DIR/.mustache-version"
CHECKSUM_FILE="$VENDOR_DIR/.mustache-checksum"

usage() {
  echo "Usage: $0 <version>"
  echo "Example: $0 4.2.0"
  exit 1
}

[ $# -eq 1 ] || usage
VERSION="$1"

mkdir -p "$VENDOR_DIR"

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

echo "Fetching mustache@$VERSION from npm..."
cd "$TMPDIR"
npm pack "mustache@$VERSION" --silent >/dev/null
tar xzf mustache-*.tgz

UMD_SRC="$TMPDIR/package/mustache.js"
LICENSE_SRC="$TMPDIR/package/LICENSE"

if [ ! -f "$UMD_SRC" ]; then
  echo "ERROR: expected mustache.js not found in package" >&2
  exit 1
fi

# Prepend bundling banner + MIT license, then the UMD source. The first three
# lines contain the "@ido4/vendored mustache v<X.Y.Z>" marker checked by
# validate-plugin.sh / release.sh.
{
  printf '// @ido4/vendored mustache v%s | bundled %s\n' "$VERSION" "$(date +%Y-%m-%d)"
  printf '// Upstream: https://github.com/janl/mustache.js — MIT License\n'
  printf '// Preserved below; do not edit this file — use scripts/update-mustache-vendor.sh\n'
  printf '/*\n'
  cat "$LICENSE_SRC"
  printf '*/\n\n'
  cat "$UMD_SRC"
} > "$BUNDLE_FILE"

# Smoke test: render a template with a section and a variable.
if ! node -e "
  const m = require('$BUNDLE_FILE');
  const out = m.render('Hello {{name}}: {{#items}}<{{v}}> {{/items}}', { name: 'ido4', items: [{v: 'a'}, {v: 'b'}] });
  if (out !== 'Hello ido4: <a> <b> ') throw new Error('unexpected render: ' + JSON.stringify(out));
" 2>&1; then
  echo "ERROR: smoke test failed — removing bundle" >&2
  rm -f "$BUNDLE_FILE"
  exit 1
fi

printf '%s\n' "$VERSION" > "$VERSION_FILE"
shasum -a 256 "$BUNDLE_FILE" | awk -v f="$(basename "$BUNDLE_FILE")" '{ print $1 "  " f }' > "$CHECKSUM_FILE"

SIZE=$(wc -c < "$BUNDLE_FILE" | tr -d ' ')
echo ""
echo "Vendored mustache v$VERSION"
echo "  Bundle:   $BUNDLE_FILE ($SIZE bytes)"
echo "  Version:  $VERSION_FILE"
echo "  Checksum: $CHECKSUM_FILE"
