#!/bin/bash
# Vendor the js-yaml UMD bundle into hooks/lib/vendored/yaml.js.
#
# Usage: ./scripts/update-yaml-vendor.sh <version>   # e.g., 4.1.1
#
# The rule-runner loads this via require('./vendored/yaml.js'). Keeping js-yaml
# out of package.json preserves the hook layer's zero-npm-dep invariant, which
# is what makes SessionStart graceful-degradation meaningful (§4.9 of
# ~/dev-projects/ido4-suite/docs/hook-and-rule-strategy.md).
#
# Pattern mirrors scripts/update-tech-spec-validator.sh. Differences:
#   - Upstream is external OSS (MIT); we preserve the license header.
#   - No cross-repo dispatch / weekly cron (frozen external dep, pin + update
#     on demand only).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
VENDOR_DIR="$PLUGIN_DIR/hooks/lib/vendored"
BUNDLE_FILE="$VENDOR_DIR/yaml.js"
VERSION_FILE="$VENDOR_DIR/.yaml-version"
CHECKSUM_FILE="$VENDOR_DIR/.yaml-checksum"

usage() {
  echo "Usage: $0 <version>"
  echo "Example: $0 4.1.1"
  exit 1
}

[ $# -eq 1 ] || usage
VERSION="$1"

mkdir -p "$VENDOR_DIR"

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

echo "Fetching js-yaml@$VERSION from npm..."
cd "$TMPDIR"
npm pack "js-yaml@$VERSION" --silent >/dev/null
tar xzf js-yaml-*.tgz

UMD_SRC="$TMPDIR/package/dist/js-yaml.js"
LICENSE_SRC="$TMPDIR/package/LICENSE"

if [ ! -f "$UMD_SRC" ]; then
  echo "ERROR: expected dist/js-yaml.js not found in package" >&2
  exit 1
fi

# Prepend a bundling banner + the upstream MIT license text, then the UMD source.
# The first three lines contain the "@ido4/vendored js-yaml v<X.Y.Z>" marker that
# validate-plugin.sh / release.sh check_bundle() grep for.
{
  printf '// @ido4/vendored js-yaml v%s | bundled %s\n' "$VERSION" "$(date +%Y-%m-%d)"
  printf '// Upstream: https://github.com/nodeca/js-yaml — MIT License\n'
  printf '// Preserved below; do not edit this file — use scripts/update-yaml-vendor.sh\n'
  printf '/*\n'
  cat "$LICENSE_SRC"
  printf '*/\n\n'
  cat "$UMD_SRC"
} > "$BUNDLE_FILE"

# Smoke test: load a small YAML doc and assert it round-trips.
if ! node -e "
  const y = require('$BUNDLE_FILE');
  const doc = y.load('version: 1\nrules:\n  - id: X\n    when: \"a === b\"\n    profiles: [hydro, scrum]\n');
  if (doc.version !== 1) throw new Error('version mismatch');
  if (!Array.isArray(doc.rules) || doc.rules.length !== 1) throw new Error('rules mismatch');
  if (doc.rules[0].id !== 'X') throw new Error('id mismatch');
  if (!Array.isArray(doc.rules[0].profiles) || doc.rules[0].profiles[0] !== 'hydro') throw new Error('profiles mismatch');
" 2>&1; then
  echo "ERROR: smoke test failed — removing bundle" >&2
  rm -f "$BUNDLE_FILE"
  exit 1
fi

printf '%s\n' "$VERSION" > "$VERSION_FILE"
shasum -a 256 "$BUNDLE_FILE" | awk -v f="$(basename "$BUNDLE_FILE")" '{ print $1 "  " f }' > "$CHECKSUM_FILE"

SIZE=$(wc -c < "$BUNDLE_FILE" | tr -d ' ')
echo ""
echo "Vendored js-yaml v$VERSION"
echo "  Bundle:   $BUNDLE_FILE ($SIZE bytes)"
echo "  Version:  $VERSION_FILE"
echo "  Checksum: $CHECKSUM_FILE"
